### ISSUE TITLE
zipfile.BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by pablobuenaposada** [appknox/pyaxmlparser#10]
I'm getting this error whatever .apk I try, can you provide an .apk example?

**Comment by ChillarAnand** [comment]
@pablobuenaposada Thanks for creating issue. 

Can you try this file https://apkpure.com/apkpure-app.html?icn=aegon&ici=image_home ?

**Comment by pablobuenaposada** [comment]
mmmmm yeah, with that one seems working so the ones I'm testing would be in some way faulty.
Anyway, I'm trying to open an apk through django TemporaryUploadedFile and seem to throw that error even with the .apk you suggested.

**Comment by ChillarAnand** [comment]
I guess streamed data from TemporaryUploadedFile is not getting saved correctly. I am closing this issue as it is not related pyaxmlparser. 

Feel free to reopen, if you find any issues with pyaxmlparser.

**Comment by karanrajpal14** [comment]
I have this issue as well. Any ideas why? Any way I can get it to work?

**Comment by ChillarAnand** [comment]
@karanrajpal14 Can your try [this apk file](https://apkpure.com/apkpure-app.html?icn=aegon&ici=image_home) and see if it works?

**Comment by subho007** [comment]
@karanrajpal14 can you share the APK file privately to `sunny+gh@appknox.com` ?

**Comment by pablobuenaposada** [comment]
mmmm... returning to this, I found that it gives BadZipfile with python 2.7, is this library supported by python 2.7 or not?

**Comment by viren-nadkarni** [comment]
No @pablobuenaposada, officially, this is python 3 only
