### ISSUE TITLE
Lots of warnings pollute output

### ISSUE THREAD

**Issue by kyak** [appknox/pyaxmlparser#19]
Hi,

gplaycli uses pyaxmlparser.

Starting from version 0.3.9, pyaxmlparser generates lots and lots of warning, such as described here: https://github.com/matlink/gplaycli/issues/188

It seems that there are unnecessary warnings in code. Can you please have a look

**Comment by ChillarAnand** [comment]
Hi @kyak, Thanks for reporting the issue. 

I think pyaxmlparser should have its own logger so that users can set appropriate logging level.

For now, you can use a temporary workaround to ignore warnings.

```py
import warnings

from pyaxmlparser import APK


file = '/home/chillar/projects/android/apps/adbd-Insecure-v2.00.apk'

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    apk = APK(file)
    print(apk.package)
```

**Comment by kyak** [comment]
Hi @ChillarAnand,

It seems that gplaycli developer doesn't see this as an issue that they have to fix: https://github.com/matlink/gplaycli/issues/188#issuecomment-430525603

From this point of view, they may be correct. I was wondering, what are your plans to make it possible for users to specify appropriate logging level?

**Comment by subho007** [comment]
Tracking this at #28
