### ISSUE TITLE
Free apk file after manipulation

### ISSUE THREAD

**Issue by Baneeishaque** [appknox/pyaxmlparser#21]
The Code :

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            apk = APK(apk_file)
            # print(apk.package)
            # print(apk.version_name)
            apk_version_name = apk.version_name
            # print(apk.version_code)
            apk_version_code = apk.version_code
            # print(apk.icon_info)
            # print(apk.icon_data)
            apk_name=apk.application
            # print('Apk Name : '+apk_name)
            print(apk_name+' '+apk_version_name+'_'+apk_version_code+'.apk')
            # os.rename(apk_file, apk_name+' '+apk_version_name+'_'+apk_version_code+'.apk')
            # copyfile(apk_file, apk_name+' '+apk_version_name+'_'+apk_version_code+'.apk')
            # os.remove(apk_file)
            shutil.move(apk_file, apk_name+' '+apk_version_name+'_'+apk_version_code+'.apk')

Execution :

```
USBDebug 1.0_1.apk
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\shutil.py", line 557, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'me.tennkia.apr.apk' -> 'USBDebug 1.0_1.apk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apkdl_downloader.py", line 70, in <module>
    shutil.move(apk_file, apk_name+' '+apk_version_name+'_'+apk_version_code+'.apk')
  File "C:\Program Files\Python37\lib\shutil.py", line 572, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'me.tennkia.apr.apk'
```

**Comment by subho007** [comment]
@Baneeishaque this is a problem with your code in this line:

`shutil.move(apk_file, apk_name+' '+apk_version_name+'_'+apk_version_code+'.apk')`

Move will not work since the APK file is still open for operation
