### ISSUE TITLE
Failure case when the package is used as the default app name

### ISSUE THREAD

**Issue by jflbr** [appknox/pyaxmlparser#22]
When the manifest does not define the application name, the lib sets its default value to the package name using the `package` property.
But this raises an error because the property is used as a regular function/callable.

Concerned lines:

https://github.com/appknox/pyaxmlparser/blob/8a5ad5b5e9de9edb5deca26999649bed1d215554/pyaxmlparser/core.py#L125

https://github.com/appknox/pyaxmlparser/blob/8a5ad5b5e9de9edb5deca26999649bed1d215554/pyaxmlparser/core.py#L136

**Comment by subho007** [comment]
Thanks for fixing it. This is merged #23
