### ISSUE TITLE
Error with the application's Icon

### ISSUE THREAD

**Issue by Ahmed-Salama96** [appknox/pyaxmlparser#30]
When i trying to get the app's icon with 'apk.icon_data', I get the following error:

-------------------------
Out of range dimension unit index for 65038.00399593472: 9
Out of range dimension unit index for 65038.00399593472: 10
Out of range dimension unit index for 32051.19728172544: 10
Out of range dimension unit index for 0.488437427482368: 8
Out of range dimension unit index for 32051.19728172544: 10
Out of range dimension unit index for 0.488437427482368: 8
Out of range dimension unit index for 0.488437427482368: 8
Out of range dimension unit index for 4082892.0: 13
Out of range dimension unit index for 4060610.0: 15
Out of range dimension unit index for 32133.11916175872: 12
Out of range dimension unit index for 123.12000590919679: 9
Out of range dimension unit index for 0.9924011500961792: 9
--------------------

**Comment by subho007** [comment]
@Ahmed-Salama96 can you send me the apk file to sunny@appknox.com ?

**Comment by subho007** [comment]
No response hence closing the issue
