### ISSUE TITLE
License clarifications

### ISSUE THREAD

**Issue by armijnhemel** [appknox/pyaxmlparser#32]
hello,

the top level file of this project says MIT license, but several files inside the pyaxmlparser directory have a very clear Apache license as they were imported from Androguard (Apache 2 licensed). Could you please clarify this, as right now it seems that the entire project is under MIT, which is not true.

**Comment by subho007** [comment]
The implementation of the project is in MIT. But will change the overall project aspect to Apache 2 license as you have mentioned

**Comment by armijnhemel** [comment]
It is perfectly fine to have your own code under MIT of course, but if you start combining it with other licenses then the combination of the code is not automatically under MIT :-)

**Comment by subho007** [comment]
Thanks for the help. Appreciate it 👍
