### ISSUE TITLE
_get_res_string_value parsing error

### ISSUE THREAD

**Issue by jtjisgod** [appknox/pyaxmlparser#41]
![image](https://user-images.githubusercontent.com/15524302/60763576-658ef000-a0b2-11e9-87b4-18cbb255ad77.png)
I parsed some string data from public xml and i tried bringing text value with _get_res_string_value("@string/text"). but it dosen't work! So, i found a mistake code from your core.py. "@string/" is 8, but you are slicing at 9. so, `string_key` is to be `ext` not `text`.

**Comment by cosmosgenius** [comment]
closed in #42. Thanks for the Issue and PR 👍
