### ISSUE TITLE
show "Failed to get the attribute with namespace" when try to decode HKnews.apk

### ISSUE THREAD

**Issue by bs111** [appknox/pyaxmlparser#45]
win 10  pro  1903
python 3.7.4
pyaxmlparser-0.3.20 
the apk please see to 
[HKNews2.zip](https://github.com/appknox/pyaxmlparser/files/3666556/HKNews2.zip)

>>> from pyaxmlparser import APK
>>> apk=APK(r"G:\MyPython\Studty\1.3处理apk获取apk的xml格式的图标\HKNews2.apk")
Failed to get the attribute with namespace
Failed to get the attribute with namespace
Failed to get the attribute with namespace
Failed to get the attribute with namespace
Failed to get the attribute with namespace

>>> os.chdir(r"G:\MyPython\Studty\1.3处理apk获取apk的xml格式的图标")
>>> apk=APK("HKNews2.apk")
Failed to get the attribute with namespace
Failed to get the attribute with namespace
Failed to get the attribute with namespace
Failed to get the attribute with namespace
Failed to get the attribute with namespace
>>>

**Comment by zhangao0086** [comment]
+1

**Comment by subho007** [comment]
I’ll have a look at this today 👍

**Comment by kyak** [comment]
Same problem..

**Comment by kyak** [comment]
Ok, so this happens with each and every apk. Might have to do with my versions of dependencies:
python-lxml is 4.4.2 and python-click is 7.0.

This, in turn, breaks gplaycli with --update switch.

**Comment by AyanPerez** [comment]
Same problem..

**Comment by AyanPerez** [comment]
I have the same problem..

**Comment by AyanPerez** [comment]
I have the same problem

**Comment by vapniks** [comment]
Same problem here. 
I ran pdb and found that the warning message is emitted by the `get_value_from_tag` function in `core.py` when it tries to get one of the following attributes: `maxSdkVersion`, `description`, `permissionGroup`, `label`, or `protectionLevel`
However, sometimes it is successful in getting those attributes, and no warning message is emitted.

**Comment by Pnikanti** [comment]
Is there anything new regarding this issue? Pyaxmlparser still manages to get the data from the APK perfectly fine on my case, but it would be nice to know the root cause of this problem and suppress the warnings without any hacky ways.

**Comment by subho007** [comment]
@kyak is pyaxmlparser still a problem ?

**Comment by kyak** [comment]
> @kyak is pyaxmlparser still a problem ?

No idea. I'm not using these anymore.

**Comment by subho007** [comment]
The latest version of pyaxmlparser fixes all of these 👍
