### ISSUE TITLE
"x509 is not defined" in calling apk.get_certificates()

### ISSUE THREAD

**Issue by Venonatory** [appknox/pyaxmlparser#54]
In "pyaxmlparser/core.py", you use "x509" and "cms", but they haven't be imported.
And i read "requirements.txt", but i can't find anything about "x509" and "cms".
After i search in google, find "asn1crypto".

I think you should add "asn1crypto" in "requirements.txt" and import them in "pyaxmlparser/core.py"

**Comment by subho007** [comment]
Agreed this is a miss, will be fixing this

**Comment by subho007** [comment]
This is being tracked at #55 👍

**Comment by subho007** [comment]
@Venonatory new version released in Pypi, you can go ahead and use it now 👍
