### ISSUE TITLE
[LICENSE] Add name of copyright owner and date

### ISSUE THREAD

**Issue by flaminestone** [appknox/pyaxmlparser#57]
Can you add name of copyright owner and date information to license file in package please. At now, there are only placeholder in this place
https://github.com/appknox/pyaxmlparser/blob/master/LICENSE#L189

**Comment by subho007** [comment]
Fixed in https://github.com/appknox/pyaxmlparser/pull/58

**Comment by subho007** [comment]
Ref: https://www.apache.org/licenses/LICENSE-2.0.html
