### ISSUE TITLE
Correct man path

### ISSUE THREAD

**Issue by ford--prefect** [appknox/pyaxmlparser#62]
Currently, in [setup.py#L17](https://github.com/appknox/pyaxmlparser/blob/master/setup.py#L17) the man path is incorrect.
Instead of `man/man1` it should be `share/man/man1`.

**Comment by cosmosgenius** [comment]
Could you provide some links to validate the change. The current implementation is based on nose repo https://github.com/nose-devs/nose/blob/master/setup.py#L109

**Comment by ford--prefect** [comment]
The man-page of the [file system hierarchy](https://www.man7.org/linux/man-pages/man7/hier.7.html) might serve as sufficiently credible source?

**Comment by chenrui333** [comment]
yeah, the man path is incorrect.

**Comment by subho007** [comment]
This is released: https://pypi.org/project/pyaxmlparser/0.3.30/
