### ISSUE TITLE
How I get icon 

### ISSUE THREAD

**Issue by shashankx86** [appknox/pyaxmlparser#63]
How I get apk icon 
its showing 
![image](https://user-images.githubusercontent.com/64682801/158419190-765f00e2-147c-4a53-9dc1-6d54fbbcfce1.png)

**Comment by subho007** [comment]
You need to save this in a file, this is the image in binary format

**Comment by shashankx86** [comment]
> You need to save this in a file, this is the image in binary format

How I do that ?

**Comment by rajan262** [comment]
@shashankx86 You can open a file stream in writable binary mode and write this data into that file. For example:
