### ISSUE TITLE
Many errors on some APKs

### ISSUE THREAD

**Issue by pasha-zzz** [appknox/pyaxmlparser#73]
"invalid decoded string length" errors on apk parsing...

F.e. https://alfamobile-web.servicecdn.ru/latest/alfa-bank.apk
> apkinfo alfa-bank.apk
> APK: alfa-bank.apk
> invalid decoded string length
> invalid decoded string length
> invalid decoded string length
> invalid decoded string length
> invalid decoded string length
> invalid decoded string length
> App name: Альфа-Банк
> Package: ru.alfabank.mobile.android
> Version name: 12.07.04
> Version code: 2042070400
> Is it Signed: True
> Is it Signed with v1 Signatures: False
> Is it Signed with v2 Signatures: True
> Is it Signed with v3 Signatures: False

And some more:
https://cdn.sberbank.ru/appdistr/SberbankOnline.apk
https://mobile-apps-prod.cdn-tinkoff.ru/tinkoff-bank-6-27-0-8011.apk

**Comment by subho007** [comment]
Published a new version: https://pypi.org/project/pyaxmlparser/0.3.29/

Upgrade the package. 
Use with the following command:

`apkinfo --silent <path-to.apk>`
